### ISSUE TITLE
Créer une page pour permettre aux médecins de visualiser les occurrences de son patient

### ISSUE THREAD

**Issue by Kagelmacher** [GeoHealth/HAppi_frontend#2]
- [x] Créer une application angular 2
- [x] Réaliser mockups
- [ ] Implémenter l'interface graphique
- [x] GET /shared_occurrence avec le token
- [ ] Affichage de graphes sexys

**Comment by seza443** [comment]
Based on: https://github.com/AngularClass/angular2-webpack-starter

**Comment by seza443** [comment]
and inspired by http://akveo.github.io/ng2-admin/
