### ISSUE TITLE
Map (Google Map) avec des périmètres plus ou moins grand selon le nombre d'occurrences d'un symptôme qui ont eues lieues à cet endroit

### ISSUE THREAD

**Issue by seza443** [GeoHealth/HAppi_frontend#8]
![image](https://cloud.githubusercontent.com/assets/6939778/24149934/850a14e4-0e44-11e7-99af-0ae8865f14b2.png)

**Comment by seza443** [comment]
https://www.amcharts.com/demos/map-bubbles/

**Comment by seza443** [comment]
https://github.com/akveo/ng2-admin/blob/master/src/app/theme/components/baAmChart/baAmChart.component.ts

**Comment by seza443** [comment]
http://akveo.com/ng2-admin/#/pages/maps/bubblemaps

**Comment by Kagelmacher** [comment]
On voudrait des messages de ce style (http://www.concepteur-internet.fr/test_carto1.php) sur les clusters de marker pour afficher les symptoms
